# Week 4: In-Class Exercise - Data Filtering & Selection

## Objective
Practice filtering techniques using the same Education Statistics dataset you cleaned last week.

## Time: ~30 minutes

## What you'll practice:
1. **Single conditions** with comparison operators
2. **Combining conditions** with & (AND), | (OR), ~ (NOT)
3. **Convenience methods**: .isin(), .between(), .str.contains()
4. **Building real questions** from data

## Dataset
Same Education Statistics from the Colombian Ministry of Education (MEN) you cleaned in Week 3.

---

## Setup
Run this cell to load libraries, load the dataset, and apply the quick clean from Week 3.

In [3]:
import pandas as pd
import numpy as np

# Load the Education Statistics dataset
df = pd.read_csv('../semana03/data/educacion_estadisticas.csv')

# Quick clean (applying what we learned in Week 3)
df['departamento'] = df['departamento'].str.upper().str.strip()
df['ano'] = df['ano'].fillna(0).astype(int)
df = df.drop_duplicates()
df = df.dropna(subset=['departamento'])

print(f"Dataset loaded and cleaned: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Years: {sorted(df['ano'].unique())}")
print(f"Departments: {df['departamento'].nunique()} unique")
df.head()

Dataset loaded and cleaned: 455 rows, 37 columns
Years: [np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Departments: 41 unique

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2023,68,SANTANDER,405256,95.80,95.64,71.27,92.98,83.40,56.02,...,7.65,2.95,91.82,12.95,6.92,7.99,2.95,7.32,11.34,4.07
1,2024,86,PUTUMAYO,81100,80.03,80.01,50.77,78.12,66.49,38.12,...,6.07,3.02,90.68,10.04,4.82,8.50,3.02,7.56,12.33,4.57
2,2016,52,NARIÑO,"394,574",71.10,NaN,38.56,68.32,56.56,29.80,...,1.89,0.04,97.71,3.07,1.92,2.64,0.04,2.36,3.79,1.34
3,2024,50,META,221911,90.34,90.29,65.69,89.17,76.00,48.10,...,6.84,2.85,91.18,11.36,5.61,9.27,2.85,9.27,12.53,3.49
4,2020,5,ANTIOQUIA,1151149,93.59,93.43,70.25,88.26,83.38,47.45,...,NaN,0.79,92.19,11.46,7.12,6.48,0.79,5.92,9.37,3.17

---

## Part 1: Single Conditions (8 minutes)

Start with simple, one-condition filters using comparison operators.

### Task 1.1: Filter by exact value
Get all rows where the year (`ano`) is 2023.

**Pattern:** `df[df['column'] == value]`

Print how many rows you found.

In [4]:
# YOUR CODE HERE
# Step 1: Create the filter
# Step 2: Print the number of rows
# Step 3: Display the first few rows
# Step 1: Create the filter

df_2023 = df[df["ano"] == 2023]

# Step 2: Print the number of rows
print("Number of rows for 2023:", len(df_2023))

# Step 3: Display the first few rows
df_2023.head()

Number of rows for 2023: 33

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2023,68,SANTANDER,405256,95.80,95.64,71.27,92.98,83.40,56.02,...,7.65,2.95,91.82,12.95,6.92,7.99,2.95,7.32,11.34,4.07
7,2023,73,TOLIMA,239730,99.13,99.04,76.38,98.24,83.94,54.77,...,6.47,4.21,91.72,10.13,5.28,8.61,4.21,9.19,10.89,3.31
15,2023,94,GUAINÍA,16704,71.61,71.55,62.35,70.20,36.75,10.67,...,NaN,5.96,80.41,14.54,7.97,15.69,5.96,19.12,14.73,5.24
39,2023,25,CUNDINAMARCA,sin dato,93.59,93.32,62.91,88.71,85.25,56.55,...,6.61,4.09,92.79,11.05,5.40,8.29,4.09,7.09,12.23,3.58
50,2023,99,VICHADA,33816,67.63,67.63,51.88,75.84,29.65,11.24,...,14.59,0.68,75.32,12.80,6.05,17.37,0.68,22.77,11.74,5.29

### Task 1.2: Filter with greater than
Find all rows where the total dropout rate (`desercion`) is greater than 5%.

**Question:** How many department-year combinations have a dropout rate above 5%?

In [5]:

df_desercion_5 = df[df["desercion"] > 5]

print("Rows with dropout > 5%:", len(df_desercion_5))

df_desercion_5.head()

Rows with dropout > 5%: 92

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
1,2024,86,PUTUMAYO,81100,80.03,80.01,50.77,78.12,66.49,38.12,...,6.07,3.02,90.68,10.04,4.82,8.50,3.02,7.56,12.33,4.57
9,2017,94,GUAINÍA,11965,80.00,79.98,59.60,78.83,36.62,8.82,...,15.53,7.92,78.42,19.29,13.37,3.13,7.92,3.35,3.28,0.38
13,2020,86,PUTUMAYO,"80,810",84.42,84.41,50.72,80.58,73.07,39.50,...,5.78,0.25,90.59,9.57,6.14,6.81,0.25,5.74,10.17,4.66
15,2023,94,GUAINÍA,16704,71.61,71.55,62.35,70.20,36.75,10.67,...,NaN,5.96,80.41,14.54,7.97,15.69,5.96,19.12,14.73,5.24
17,2011,95,GUAVIARE,31133,64.04,64.02,32.16,65.42,45.16,20.08,...,0.18,0.00,91.73,0.00,2.17,2.41,0.00,2.08,3.50,1.86

### Task 1.3: Filter with less than
Find all rows where net coverage (`cobertura_neta`) is less than 70%.

**Question:** Which departments have the lowest coverage? Look at the `departamento` column in your result.

In [6]:
# YOUR CODE HERE
df_cobertura_70 = df[df["cobertura_neta"] < 70]

print("Rows with coverage < 70%:", len(df_cobertura_70))

df_cobertura_70[["departamento", "cobertura_neta"]].head()

Rows with coverage < 70%: 39

   departamento  cobertura_neta
17     GUAVIARE           64.02
23      VICHADA           68.25
33        HUILA           -9.26
43       VAUPÉS           53.45
45     GUAVIARE           59.18

---

## Part 2: Combining Conditions (8 minutes)

Now combine multiple conditions using `&` (AND), `|` (OR), and `~` (NOT).

**Remember:** Always wrap each condition in parentheses!

### Task 2.1: AND condition
Find rows where the year is 2023 AND the dropout rate is above 5%.

**Pattern:** `df[(condition1) & (condition2)]`

**Question:** Which departments had high dropout in 2023?

In [8]:
# YOUR CODE HERE
# Show: departamento, ano, desercion columns
df_2023_high_dropout = df[
    (df["ano"] == 2023) & (df["desercion"] > 5)
]

display(df_2023_high_dropout[["departamento", "ano", "desercion"]])

        departamento   ano  desercion
15           GUAINÍA  2023       6.03
112         AMAZONAS  2023       5.01
150          CAQUETÁ  2023       6.89
383  VALLE DEL CAUCA  2023       5.22
384        RISARALDA  2023       5.60
408         GUAVIARE  2023       5.62

### Task 2.2: OR condition
Find all rows from either Antioquia OR Valle del Cauca.

**Pattern:** `df[(condition1) | (condition2)]`

**Hint:** The department names should be uppercase (we cleaned them in setup).

In [11]:
# YOUR CODE HERE
df_selected = df[
    (df["departamento"] == "ANTIOQUIA") |(df["departamento"] == "VALLE DEL CAUCA")
]

display(df_selected)

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
4,2020,5,ANTIOQUIA,1151149,93.59,93.43,70.25,88.26,83.38,47.45,...,NaN,0.79,92.19,11.46,7.12,6.48,0.79,5.92,9.37,3.17
24,2012,5,ANTIOQUIA,1278686,92.79,92.65,73.20,92.65,74.84,43.50,...,3.95,0.20,93.05,5.55,4.02,1.93,0.20,1.67,2.95,1.10
34,2011,5,ANTIOQUIA,1288473,94.01,93.85,70.28,94.12,75.68,44.37,...,2.06,0.07,94.56,2.54,2.96,4.25,0.07,4.56,5.27,1.68
55,2024,5,ANTIOQUIA,1128314,90.02,89.85,68.83,87.32,77.04,52.81,...,7.27,1.90,91.58,11.75,5.80,9.26,1.90,8.78,13.31,4.19
91,2012,76,VALLE DEL CAUCA,894698,88.26,88.09,60.32,86.16,71.21,40.62,...,3.29,0.20,93.91,5.28,3.33,1.64,0.20,1.39,2.40,1.01
101,2018,5,ANTIOQUIA,1147598,84.72,94.11,67.98,NaN,81.29,43.83,...,6.91,0.19,91.00,10.05,5.41,3.13,0.19,3.14,4.22,1.29
121,2023,5,ANTIOQUIA,"1,131,546",92.07,91.89,72.25,88.03,79.26,53.34,...,8.47,1.94,89.38,13.34,6.49,9.69,1.94,9.54,13.52,4.23
124,2015,5,ANTIOQUIA,1262800,89.92,89.79,61.07,89.02,74.17,42.61,...,6.84,0.20,91.59,10.56,5.64,2.83,0.20,2.26,4.55,1.95
129,2013,5,ANTIOQUIA,1272458,92.06,91.93,67.61,91.53,75.66,42.71,...,4.84,0.12,93.02,6.96,5.17,1.57,0.12,1.41,2.27,1.12
135,2011,76,VALLE DEL CAUCA,906602,88.51,88.33,56.25,86.83,72.17,42.06,...,5.07,0.58,92.95,7.90,6.37,2.30,0.58,2.09,3.22,1.09
154,2015,76,VALLE DEL CAUCA,875476,84.44,84.26,50.96,82.63,69.59,39.64,...,6.18,0.69,93.14,9.70,4.99,0.92,0.69,0.72,1.44,0.60
210,2021,76,VALLE DEL CAUCA,839566,81.86,81.67,55.21,76.54,72.48,47.88,...,8.31,1.04,88.67,11.48,7.61,4.76,1.04,4.06,6.92,2.80
212,2024,76,VALLE DEL CAUCA,836702,76.03,75.84,54.51,73.57,65.01,45.72,...,7.54,4.89,90.12,12.01,5.86,8.84,4.89,8.34,11.98,4.38
235,2019,76,VALLE DEL CAUCA,854243,81.68,81.46,55.95,76.71,72.69,41.95,...,7.25,0.71,91.13,10.80,5.81,1.17,0.71,1.06,1.64,0.61
237,2017,5,ANTIOQUIA,1270105,86.10,86.00,56.58,83.30,73.93,42.85,...,7.16,0.19,90.80,10.64,5.66,6.52,0.19,6.31,8.94,2.97
242,2013,76,VALLE DEL CAUCA,887988,87.56,87.37,58.92,84.98,71.27,40.61,...,3.39,0.25,94.83,5.13,3.52,1.30,0.25,1.09,1.90,0.86
260,2014,76,VALLE DEL CAUCA,880625,85.52,85.34,53.64,83.48,70.81,39.12,...,2.24,0.18,96.62,3.61,2.14,0.82,0.18,0.81,1.06,0.52
289,2020,76,VALLE DEL CAUCA,NaN,82.18,NaN,57.87,77.11,73.15,44.44,...,6.86,1.88,92.43,9.92,6.50,5.72,1.88,5.05,8.31,2.85
326,2022,76,VALLE DEL CAUCA,"848,047",79.71,79.50,59.59,75.32,68.57,47.39,...,8.01,0.79,88.78,12.15,6.48,6.33,0.79,6.22,8.55,3.83
328,2017,76,VALLE DEL CAUCA,873860,80.40,80.21,49.95,76.38,71.03,40.74,...,6.70,0.84,91.59,10.03,4.78,1.45,0.84,1.35,1.93,0.78
339,2018,76,VALLE DEL CAUCA,861316,79.27,80.36,53.98,76.19,71.45,40.20,...,7.52,0.50,91.63,11.36,6.34,1.10,0.50,1.06,1.44,0.59
383,2023,76,VALLE DEL CAUCA,"842,813",78.09,77.90,58.61,74.78,66.48,46.35,...,8.43,5.19,88.92,12.93,7.00,9.08,5.19,9.01,11.93,4.03
421,2019,5,ANTIOQUIA,"1,149,985",94.00,93.83,67.86,90.24,82.60,45.04,...,7.59,0.18,90.73,11.56,5.68,3.19,0.18,2.92,4.65,1.37
437,2022,5,ANTIOQUIA,1134099,93.50,93.32,73.12,88.54,81.83,52.35,...,8.17,0.25,89.52,12.49,6.35,6.49,0.25,6.58,8.78,3.34
465,2014,5,ANTIOQUIA,1266533,90.97,NaN,64.15,90.68,75.13,41.79,...,2.59,0.07,96.35,4.20,3.09,2.09,0.07,1.61,3.35,1.84
469,2021,5,ANTIOQUIA,"1,149,861",92.62,92.45,69.22,87.05,82.80,49.85,...,7.66,0.30,89.26,10.65,6.93,5.84,0.30,5.07,8.68,3.02
475,2016,76,VALLE DEL CAUCA,873706,81.40,81.23,47.12,78.38,69.91,41.43,...,6.94,0.64,91.33,10.69,5.71,1.29,0.64,1.24,1.70,0.54

### Task 2.3: NOT condition
Get all rows EXCEPT those from the "NACIONAL" department (the national aggregate).

**Two ways to do this:**
- `df[df['departamento'] != 'NACIONAL']`
- `df[~(df['departamento'] == 'NACIONAL')]`

Try both and verify you get the same number of rows.

In [15]:
# YOUR CODE HERE
# Method 1: using !=
df_not_nacional_1 = df[df["departamento"] != "NACIONAL"]
# Method 2: using ~
df_not_nacional_2 = df[~(df["departamento"] == "NACIONAL")]
# Compare the row counts
print(df_not_nacional_1.shape[0])
print(df_not_nacional_2.shape[0])

455
455

---

## Part 3: Convenience Methods (7 minutes)

Use `.isin()`, `.between()`, and `.str.contains()` to write cleaner filters.

### Task 3.1: .isin() - Match a list
Find all rows from the following departments: ANTIOQUIA, BOGOTA D.C., VALLE DEL CAUCA, CUNDINAMARCA.

**Pattern:** `df[df['column'].isin([list_of_values])]`

In [16]:
# YOUR CODE HERE
departments_list = [
    "ANTIOQUIA",
    "BOGOTA D.C.",
    "VALLE DEL CAUCA",
    "CUNDINAMARCA"
]

df_selected_departments = df[
    df["departamento"].isin(departments_list)
]

display(df_selected_departments)

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
4,2020,5,ANTIOQUIA,1151149,93.59,93.43,70.25,88.26,83.38,47.45,...,NaN,0.79,92.19,11.46,7.12,6.48,0.79,5.92,9.37,3.17
11,2016,25,CUNDINAMARCA,577612,91.20,90.90,56.31,88.25,80.47,50.92,...,3.05,0.54,95.30,4.97,2.56,2.40,0.54,1.86,3.71,1.46
24,2012,5,ANTIOQUIA,1278686,92.79,92.65,73.20,92.65,74.84,43.50,...,3.95,0.20,93.05,5.55,4.02,1.93,0.20,1.67,2.95,1.10
34,2011,5,ANTIOQUIA,1288473,94.01,93.85,70.28,94.12,75.68,44.37,...,2.06,0.07,94.56,2.54,2.96,4.25,0.07,4.56,5.27,1.68
39,2023,25,CUNDINAMARCA,sin dato,93.59,93.32,62.91,88.71,85.25,56.55,...,6.61,4.09,92.79,11.05,5.40,8.29,4.09,7.09,12.23,3.58
55,2024,5,ANTIOQUIA,1128314,90.02,89.85,68.83,87.32,77.04,52.81,...,7.27,1.90,91.58,11.75,5.80,9.26,1.90,8.78,13.31,4.19
61,2020,25,CUNDINAMARCA,592264,93.68,93.42,64.47,90.32,86.08,50.35,...,6.63,1.61,93.77,10.51,7.26,5.29,1.61,4.22,8.09,3.04
72,2013,25,CUNDINAMARCA,572012,90.49,90.28,61.00,85.47,82.08,47.98,...,1.12,0.03,96.84,1.93,1.41,1.90,0.03,1.39,2.95,1.52
91,2012,76,VALLE DEL CAUCA,894698,88.26,88.09,60.32,86.16,71.21,40.62,...,3.29,0.20,93.91,5.28,3.33,1.64,0.20,1.39,2.40,1.01
101,2018,5,ANTIOQUIA,1147598,84.72,94.11,67.98,NaN,81.29,43.83,...,6.91,0.19,91.00,10.05,5.41,3.13,0.19,3.14,4.22,1.29
121,2023,5,ANTIOQUIA,"1,131,546",92.07,91.89,72.25,88.03,79.26,53.34,...,8.47,1.94,89.38,13.34,6.49,9.69,1.94,9.54,13.52,4.23
124,2015,5,ANTIOQUIA,1262800,89.92,89.79,61.07,89.02,74.17,42.61,...,6.84,0.20,91.59,10.56,5.64,2.83,0.20,2.26,4.55,1.95
129,2013,5,ANTIOQUIA,1272458,92.06,91.93,67.61,91.53,75.66,42.71,...,4.84,0.12,93.02,6.96,5.17,1.57,0.12,1.41,2.27,1.12
135,2011,76,VALLE DEL CAUCA,906602,88.51,88.33,56.25,86.83,72.17,42.06,...,5.07,0.58,92.95,7.90,6.37,2.30,0.58,2.09,3.22,1.09
154,2015,76,VALLE DEL CAUCA,875476,84.44,84.26,50.96,82.63,69.59,39.64,...,6.18,0.69,93.14,9.70,4.99,0.92,0.69,0.72,1.44,0.60
176,2017,25,CUNDINAMARCA,"579,364",91.80,91.56,57.22,89.27,81.65,51.57,...,NaN,0.54,95.79,5.22,3.13,2.43,0.54,1.92,3.67,1.54
181,2014,25,CUNDINAMARCA,573948,89.99,89.79,58.96,NaN,81.31,48.48,...,0.69,0.01,97.80,1.15,1.25,1.73,0.01,1.23,2.73,1.43
210,2021,76,VALLE DEL CAUCA,839566,81.86,81.67,55.21,76.54,72.48,47.88,...,8.31,1.04,88.67,11.48,7.61,4.76,1.04,4.06,6.92,2.80
212,2024,76,VALLE DEL CAUCA,836702,76.03,75.84,54.51,73.57,65.01,45.72,...,7.54,4.89,90.12,12.01,5.86,8.84,4.89,8.34,11.98,4.38
226,2019,25,CUNDINAMARCA,NaN,96.14,95.86,65.93,94.63,85.96,49.70,...,5.30,0.67,94.29,8.57,4.59,1.74,0.67,1.33,2.76,0.82
227,2011,25,CUNDINAMARCA,NaN,92.13,91.93,67.19,88.12,81.38,47.57,...,0.89,0.04,96.62,1.26,1.93,2.70,0.04,1.99,4.18,1.78
235,2019,76,VALLE DEL CAUCA,854243,81.68,81.46,55.95,76.71,72.69,41.95,...,7.25,0.71,91.13,10.80,5.81,1.17,0.71,1.06,1.64,0.61
237,2017,5,ANTIOQUIA,1270105,86.10,86.00,56.58,83.30,73.93,42.85,...,7.16,0.19,90.80,10.64,5.66,6.52,0.19,6.31,8.94,2.97
242,2013,76,VALLE DEL CAUCA,887988,87.56,87.37,58.92,84.98,71.27,40.61,...,3.39,0.25,94.83,5.13,3.52,1.30,0.25,1.09,1.90,0.86
260,2014,76,VALLE DEL CAUCA,880625,85.52,85.34,53.64,83.48,70.81,39.12,...,2.24,0.18,96.62,3.61,2.14,0.82,0.18,0.81,1.06,0.52
266,2021,25,CUNDINAMARCA,610367,90.84,90.58,60.68,85.96,84.79,50.40,...,6.59,1.03,92.02,10.10,7.20,5.20,1.03,3.59,8.39,3.37
281,2022,25,CUNDINAMARCA,sin dato,96.46,96.16,67.26,91.19,88.69,54.67,...,6.12,1.21,92.63,10.00,4.96,6.81,1.21,5.58,10.32,4.01
289,2020,76,VALLE DEL CAUCA,NaN,82.18,NaN,57.87,77.11,73.15,44.44,...,6.86,1.88,92.43,9.92,6.50,5.72,1.88,5.05,8.31,2.85
325,2015,25,CUNDINAMARCA,576429,90.72,90.47,55.93,NaN,80.91,50.50,...,NaN,0.43,95.57,5.80,3.30,2.14,0.43,1.67,3.26,1.44
326,2022,76,VALLE DEL CAUCA,"848,047",79.71,79.50,59.59,75.32,68.57,47.39,...,8.01,0.79,88.78,12.15,6.48,6.33,0.79,6.22,8.55,3.83
328,2017,76,VALLE DEL CAUCA,873860,80.40,80.21,49.95,76.38,71.03,40.74,...,6.70,0.84,91.59,10.03,4.78,1.45,0.84,1.35,1.93,0.78
339,2018,76,VALLE DEL CAUCA,861316,79.27,80.36,53.98,76.19,71.45,40.20,...,7.52,0.50,91.63,11.36,6.34,1.10,0.50,1.06,1.44,0.59
383,2023,76,VALLE DEL CAUCA,"842,813",78.09,77.90,58.61,74.78,66.48,46.35,...,8.43,5.19,88.92,12.93,7.00,9.08,5.19,9.01,11.93,4.03
399,2012,25,CUNDINAMARCA,571082,91.17,90.97,63.61,87.82,81.53,47.27,...,1.22,0.06,97.25,1.97,1.97,2.02,0.06,1.53,3.20,1.28
421,2019,5,ANTIOQUIA,"1,149,985",94.00,93.83,67.86,90.24,82.60,45.04,...,7.59,0.18,90.73,11.56,5.68,3.19,0.18,2.92,4.65,1.37
422,2018,25,CUNDINAMARCA,547875,92.49,97.91,67.00,98.58,86.40,50.34,...,5.00,0.74,94.56,7.80,5.03,2.11,0.74,1.60,3.34,1.14
437,2022,5,ANTIOQUIA,1134099,93.50,93.32,73.12,88.54,81.83,52.35,...,8.17,0.25,89.52,12.49,6.35,6.49,0.25,6.58,8.78,3.34
465,2014,5,ANTIOQUIA,1266533,90.97,NaN,64.15,90.68,75.13,41.79,...,2.59,0.07,96.35,4.20,3.09,2.09,0.07,1.61,3.35,1.84
469,2021,5,ANTIOQUIA,"1,149,861",92.62,92.45,69.22,87.05,82.80,49.85,...,7.66,0.30,89.26,10.65,6.93,5.84,0.30,5.07,8.68,3.02
475,2016,76,VALLE DEL CAUCA,873706,81.40,81.23,47.12,78.38,69.91,41.43,...,6.94,0.64,91.33,10.69,5.71,1.29,0.64,1.24,1.70,0.54

### Task 3.2: .between() - Numeric range
Find all rows where the approval rate (`aprobacion`) is between 90 and 100 (inclusive).

**Pattern:** `df[df['column'].between(low, high)]`

In [19]:
# YOUR CODE HERE
df_high_approval = df[
    df["aprobacion"].between(90, 100)
]

display(df_high_approval)

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
2,2016,52,NARIÑO,"394,574",71.10,NaN,38.56,68.32,56.56,29.80,...,1.89,0.04,97.71,3.07,1.92,2.64,0.04,2.36,3.79,1.34
5,2015,52,NARIÑO,396138,73.53,NaN,39.88,71.43,56.46,29.95,...,2.35,0.03,97.47,3.39,3.28,1.35,0.03,1.04,2.27,0.95
6,2022,52,NARIÑO,307217,80.63,NaN,59.47,NaN,66.77,41.78,...,5.14,1.41,93.08,6.93,4.28,8.07,1.41,9.03,10.00,3.49
8,2011,47,MAGDALENA,333793,94.47,94.32,55.40,90.90,66.53,37.55,...,1.39,0.42,95.12,1.41,2.08,1.52,0.42,1.44,1.99,0.65
10,2011,23,CÓRDOBA,405431,94.53,94.46,67.18,93.22,68.79,37.16,...,1.12,0.22,95.13,1.37,2.71,4.07,0.22,4.18,4.53,2.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,2018,18,CAQUETÁ,98639,73.14,NaN,59.17,90.89,69.46,32.22,...,1.88,0.42,93.80,2.57,2.43,2.52,0.42,2.51,3.36,1.37
472,2014,73,TOLIMA,313709,86.36,86.30,51.27,84.15,72.77,40.72,...,5.53,0.27,91.55,8.58,4.93,0.92,0.27,0.82,1.32,0.65
474,2011,68,SANTANDER,434034,92.49,92.40,69.70,92.88,77.28,48.10,...,NaN,0.34,96.11,3.48,2.98,2.92,0.34,2.30,4.48,1.59
477,2014,19,CAUCA,sin dato,84.60,84.58,45.54,86.00,64.65,31.39,...,0.12,0.00,96.17,0.01,0.97,1.20,0.00,1.05,1.78,1.01
478,2019,18,CAQUETÁ,NaN,90.52,90.49,57.80,89.20,68.56,33.58,...,2.05,0.41,93.40,2.51,2.53,2.60,0.41,2.70,3.28,1.12

### Task 3.3: .str.contains() - Text pattern
Find all rows where the department name contains "SANTANDER".

**Pattern:** `df[df['column'].str.contains('text', na=False)]`

**Question:** Which departments match? (Hint: there should be more than one.)

In [18]:
# YOUR CODE HERE
# Print the unique department names in your result
df_santander = df[
    df["departamento"].str.contains("SANTANDER", na=False)
]

display(df_santander)
print("Matching departments:")
print(df_santander["departamento"].unique())

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2023,68,SANTANDER,405256,95.80,95.64,71.27,92.98,83.40,56.02,...,7.65,2.95,91.82,12.95,6.92,7.99,2.95,7.32,11.34,4.07
22,2019,54,NORTE DE SANTANDER,318252,92.25,92.18,64.42,NaN,76.09,41.87,...,6.19,0.85,92.43,9.56,6.46,1.37,0.85,1.34,1.83,0.77
52,2016,68,SANTANDER,402820,95.20,95.00,59.67,94.75,83.00,50.45,...,6.14,0.52,92.98,10.22,6.15,2.48,0.52,1.96,3.90,1.27
64,2013,68,SANTANDER,"419,596",93.40,93.28,60.45,92.92,80.27,48.09,...,NaN,0.47,95.30,5.58,4.41,2.04,0.47,1.48,3.29,1.35
92,2017,68,SANTANDER,"398,621",96.50,96.33,63.75,95.04,85.29,51.23,...,NaN,0.46,93.96,9.87,5.88,2.41,0.46,1.92,3.75,1.34
114,2020,68,SANTANDER,408876,95.97,95.83,68.01,93.45,85.52,51.23,...,7.10,2.84,93.97,11.15,6.84,6.26,2.84,4.70,9.96,4.02
127,2011,54,NORTE DE SANTANDER,324219,89.04,88.96,68.90,91.01,66.38,39.03,...,0.65,0.06,94.41,0.76,1.64,2.19,0.06,1.70,3.46,1.56
140,2014,54,NORTE DE SANTANDER,NaN,87.20,87.15,57.87,89.64,68.40,36.99,...,NaN,0.09,96.28,1.02,1.06,1.64,0.09,1.21,2.71,1.40
161,2024,68,SANTANDER,404490,93.06,NaN,65.07,NaN,82.32,54.99,...,6.88,2.62,92.49,12.00,6.04,7.60,2.62,6.16,11.57,4.20
165,2020,54,NORTE DE SANTANDER,325981,90.24,90.16,66.90,89.00,76.87,41.20,...,7.24,2.67,89.74,9.48,6.11,5.51,2.67,4.57,8.25,4.13
184,2018,54,NORTE DE SANTANDER,307526,93.58,91.62,65.88,NaN,74.50,40.56,...,5.50,0.40,92.65,8.60,6.34,1.41,0.40,1.35,1.94,0.81
185,2015,68,SANTANDER,NaN,94.50,94.37,59.90,94.34,82.45,47.84,...,4.90,0.81,94.70,8.18,5.13,1.62,0.81,1.12,2.64,1.31
188,2013,54,NORTE DE SANTANDER,NaN,86.42,86.37,61.14,88.74,66.27,37.86,...,1.05,0.14,96.15,1.63,1.50,1.72,0.14,1.30,2.67,1.56
192,2021,54,NORTE DE SANTANDER,328034,92.06,92.00,65.58,89.54,79.23,44.63,...,8.33,1.40,89.53,12.07,8.50,3.90,1.40,3.10,5.92,2.79
197,2014,68,SANTANDER,"413,227",93.63,93.52,57.10,93.33,81.72,47.00,...,1.73,0.49,96.59,2.80,2.27,1.76,0.49,1.36,2.80,1.36
236,2019,68,SANTANDER,405798,96.38,96.20,67.64,94.58,84.70,49.96,...,7.47,0.46,93.03,12.42,7.26,1.91,0.46,1.49,2.96,1.17
245,2022,54,NORTE DE SANTANDER,328869,91.88,91.81,69.99,NaN,76.87,46.66,...,7.95,0.73,88.89,11.55,7.54,6.03,0.73,5.71,8.54,3.55
268,2022,68,SANTANDER,405521,96.67,96.49,73.28,93.72,84.59,53.91,...,7.58,0.49,90.32,12.17,7.10,6.43,0.49,4.91,10.43,4.02
351,2017,54,NORTE DE SANTANDER,sin dato,90.40,90.30,61.33,NaN,73.65,39.83,...,4.54,1.17,94.38,7.58,5.02,1.24,1.17,1.20,1.70,0.54
373,2024,54,NORTE DE SANTANDER,330046,87.90,87.85,65.52,86.65,73.33,47.94,...,7.38,2.70,90.55,12.11,6.61,8.39,2.70,7.85,11.77,4.71
391,2018,68,SANTANDER,401463,97.79,96.06,67.51,94.88,83.83,49.63,...,7.34,0.45,93.15,12.29,7.35,1.73,0.45,1.43,2.71,0.71
395,2021,68,SANTANDER,"409,198",96.05,95.89,67.85,93.03,86.89,53.30,...,8.51,0.77,90.95,13.68,8.85,4.47,0.77,3.05,7.45,2.91
405,2012,68,SANTANDER,425904,92.21,92.11,70.17,NaN,77.82,46.84,...,2.68,0.32,94.58,4.44,3.23,2.53,0.32,1.75,4.18,1.58
438,2012,54,NORTE DE SANTANDER,322304,86.00,85.93,71.79,NaN,64.30,35.87,...,1.52,0.31,94.52,2.45,2.21,2.00,0.31,1.51,3.15,1.55
457,2023,54,NORTE DE SANTANDER,329874,91.17,91.11,68.85,88.68,75.55,49.14,...,8.49,2.56,89.26,13.56,7.94,8.19,2.56,8.84,10.09,4.09
461,2015,54,NORTE DE SANTANDER,310611,85.89,85.84,58.03,89.27,68.70,36.24,...,1.59,0.15,96.86,2.55,2.11,1.31,0.15,1.08,2.00,0.85
474,2011,68,SANTANDER,434034,92.49,92.40,69.70,92.88,77.28,48.10,...,NaN,0.34,96.11,3.48,2.98,2.92,0.34,2.30,4.48,1.59

Matching departments:
<StringArray>
['SANTANDER', 'NORTE DE SANTANDER']
Length: 2, dtype: str

---

## Part 4: Real Questions (5 minutes)

Use everything you've learned to answer these questions about the data.

### Task 4.1: Complex filter
Find departments in 2023 where:
- Net coverage is above 80% AND
- Dropout rate is below 3%

These are the "high performing" departments. Show the department name, coverage, and dropout columns.

In [21]:
# YOUR CODE HERE
df_high_performing = df[
    (df["ano"] == 2023) &
    (df["cobertura_neta"] > 80) &
    (df["desercion"] < 3)
]

display(df_high_performing[
    ["departamento", "cobertura_neta", "desercion"]
])

     departamento  cobertura_neta  desercion
51      ATLÁNTICO           93.63       2.34
73   BOGOTÁ, D.C.           92.40       2.82
276         CHOCÓ           84.91       2.32
340        BOYACÁ           91.92       2.43

### Task 4.2: Try .query()
Rewrite the filter from Task 4.1 using `.query()` instead of boolean indexing.

**Pattern:** `df.query('condition1 and condition2')`

Verify you get the same number of rows.

In [24]:
# YOUR CODE HERE
df_high_performing_query = df.query(
    "ano == 2023 and cobertura_neta > 80 and desercion < 3"
)

display(df_high_performing_query)

print("Rows with boolean indexing:",
      df_high_performing.shape[0])

print("Rows with query():",
      df_high_performing_query.shape[0])

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
51,2023,8,ATLÁNTICO,"545,813",94.06,93.63,65.86,89.59,79.14,55.30,...,6.48,6.99,91.96,9.45,4.55,6.98,6.99,7.92,7.45,2.27
73,2023,11,"BOGOTÁ, D.C.",sin dato,92.90,92.40,61.43,86.97,86.48,64.42,...,7.78,1.66,91.87,12.57,6.50,7.55,1.66,7.11,10.98,3.20
276,2023,27,CHOCÓ,"147,698",84.91,84.91,55.21,86.07,61.03,29.60,...,NaN,2.28,89.34,10.89,5.65,10.59,2.28,12.95,11.33,3.19
340,2023,15,BOYACÁ,233865,91.98,91.92,71.42,87.74,84.80,60.34,...,6.86,2.02,94.15,11.47,5.39,8.00,2.02,6.72,12.10,4.05

Rows with boolean indexing: 4
Rows with query(): 4

---

## Bonus: Design Your Own Filter (if time permits)

Think of a question you could ask about the education data. Write the filter to answer it.

Example questions:
- Which departments had improving dropout rates (2022 lower than 2020)?
- Which departments in the Llanos region (Arauca, Casanare, Meta, Vichada) have the best coverage?
- What was the range of approval rates in 2024?

In [ ]:
# YOUR QUESTION: ________________________________
# YOUR CODE HERE

---

## Summary

In this exercise you practiced:

1. **Single conditions** - `==`, `!=`, `>`, `<`, `>=`, `<=`
2. **Combining conditions** - `&` (AND), `|` (OR), `~` (NOT)
3. **Convenience methods** - `.isin()`, `.between()`, `.str.contains()`
4. **Clean syntax** - `.query()` as an alternative

Key rules:
- Use `&` `|` `~` (NOT `and` `or` `not`) for DataFrames
- Always wrap conditions in **parentheses**
- Add `na=False` to `.str.contains()`

**Next:** Complete the workshop notebook for more complex filtering scenarios and analysis.